### ISSUE TITLE
Additional dependency jar support

### ISSUE THREAD

**Issue by githubyong** [spring-projects-experimental/spring-boot-thin-launcher#121] opened 2019-11-01 07:33 UTC
sometimes we want to add integration or do fix bug for our app, and put those jars in to a "patch" dir, this dir will be loaded earlier than other jars.I tried use 'thin.classpath', but  it doesn't work well. how to support this?
```
thin.repo  \\repo
patch      \\patch jars ,or unknown integration jars 
app.jar    \\ main application
```

**Comment by dsyer** [comment] 2019-11-06 07:38
Duplicate of #109 and/or #78? You can put the "patch" jars in your local Maven cache (or in a remote repo) and they can be used via `thin.properties`.

**Closed** 2019-11-12 16:12 UTC
