### ISSUE TITLE
Maven doesn't use local cache for snapshots if there is a remote that has the dependency

### ISSUE THREAD

**Issue by githubyong** [spring-projects-experimental/spring-boot-thin-launcher#140] opened 2020-05-28 02:41 UTC
my maven local repo like this：
```
-rw-r--r-- 1 212609083 1049089  276  5月 22 09:02 risservice-mywk-common-3.12.04-SNAPSHOT.pom.lastUpdated
-rw-r--r-- 1 212609083 1049089  276  5月 22 09:02 risservice-mywk-common-3.12.04-SNAPSHOT.jar.lastUpdated
-rw-r--r-- 1 212609083 1049089 1.4K  5月 26 09:06 risservice-mywk-common-3.12.04-20200525.012556-1.pom
-rw-r--r-- 1 212609083 1049089   40  5月 26 09:06 risservice-mywk-common-3.12.04-20200525.012556-1.pom.sha1
-rw-r--r-- 1 212609083 1049089 108K  5月 26 09:06 risservice-mywk-common-3.12.04-20200525.012556-1.jar
-rw-r--r-- 1 212609083 1049089   40  5月 26 09:06 risservice-mywk-common-3.12.04-20200525.012556-1.jar.sha1
-rw-r--r-- 1 212609083 1049089 1.4K  5月 27 09:03 risservice-mywk-common-3.12.04-SNAPSHOT.pom
-rw-r--r-- 1 212609083 1049089 121K  5月 28 10:23 risservice-mywk-common-3.12.04-SNAPSHOT.jar
```

but mvn clean installed repo root like this
```
-rw-r--r-- 1 212609083 1049089 1.4K  5月 28 10:40 risservice-mywk-common-3.12.04-SNAPSHOT.pom
-rw-r--r-- 1 212609083 1049089 1.4K  5月 28 10:40 risservice-mywk-common-3.12.04-20200525.012556-1.pom
-rw-r--r-- 1 212609083 1049089   40  5月 28 10:40 risservice-mywk-common-3.12.04-20200525.012556-1.pom.sha1
-rw-r--r-- 1 212609083 1049089 108K  5月 28 10:40 risservice-mywk-common-3.12.04-SNAPSHOT.jar
-rw-r--r-- 1 212609083 1049089 108K  5月 28 10:40 risservice-mywk-common-3.12.04-20200525.012556-1.jar
-rw-r--r-- 1 212609083 1049089   40  5月 28 10:40 risservice-mywk-common-3.12.04-20200525.012556-1.jar.sha1

```
risservice-mywk-common-3.12.04-SNAPSHOT.jar lastest installed is 121k, but thin jar package process doesn't use local latest dependency jar

**Comment by dsyer** [comment] 2020-06-09 10:25
Snapshot resolution depends on the metadata (there's an XML file in that directory) not on the version labels per se. I'm not really sure what you are saying the problem is though. Does the update of snapshots fail when you try to resolve the thin jar dependencies? What are the steps to reproduce this problem? And what are the symptoms - what makes you say the thin jar is not using the latest dependency?

**Comment by githubyong** [comment] 2020-06-15 14:32
it count't resolve the latest dependency.
reproduce steps:
1.create a project module-a which dependency module-b.
2.install module-b.
3.mvn clean package module-a use thin-layout.
4.add some class to module-b and install module-b
5.mvn clean package module-a use thin-layout, and then you will see thin-layout resolved module-b.jar doesn't contain the classes in step4.
> Snapshot resolution depends on the metadata (there's an XML file in that directory) not on the version labels per se. I'm not really sure what you are saying the problem is though. Does the update of snapshots fail when you try to resolve the thin jar dependencies? What are the steps to reproduce this problem? And what are the symptoms - what makes you say the thin jar is not using the latest dependency?

**Comment by dsyer** [comment] 2020-06-15 16:25
Sorry, it seems to work for me (I used the "multi" sample in this repository and checked the jar content in a `--thin.dryrun` repository):

```
$ ls -l ~/.m2/repository/com/example/library/0.0.1-SNAPSHOT/*.jar
-rw-rw-r-- 1 dsyer dsyer 3387 Jun 15 17:19 /home/dsyer/.m2/repository/com/example/library/0.0.1-SNAPSHOT/library-0.0.1-SNAPSHOT.jar
```

```
$ java -jar application/target/application-0.0.1-SNAPSHOT.jar --thin.dryrun --thin.root=target/root
$ ls -l target/root/repository/com/example/library/0.0.1-SNAPSHOT/*.jar
-rw-rw-r-- 1 dsyer dsyer 3387 Jun 15 17:20 target/root/repository/com/example/library/0.0.1-SNAPSHOT/library-0.0.1-SNAPSHOT.jar
```

What makes you say the resolved module-b.jar in step 5 doesn't contain the new class?

**Comment by githubyong** [comment] 2020-06-16 01:49
it works well at first time.
please try to redo step 4 and step 5.

**Comment by dsyer** [comment] 2020-06-16 05:19
If it works the first time it’s going to work the second and subsequent times, I expect. There must be something different in your environment. The time stamps look odd to me: it looks like your latest (10:23) snapshot wasn’t installed correctly. I reckon if you delete that cache and re-install using `min install` it will work for you as well.

**Comment by githubyong** [comment] 2020-06-16 15:40
sorry,i forgot that i use a private maven repository,thin resolved dependency will use private repository instead of local repo.
[here](https://github.com/githubyong/thin-demo) is a minimal demo.

**Comment by dsyer** [comment] 2020-06-17 16:05
Right that helps. At least I can reproduce the problem that way. I don't think I know how to fix it though, since it seems to be the "normal" behaviour of Maven - the local cache is ignored (I think because it doesn't have the right metadata) if there is a remote that has the same artifact. It's possible this only applies to snapshots, but I'm not sure about that. The only workarounds I know are the one you found (to deploy the library before you run the app jar), and to switch off the remote repository (put it in a profile or something and deactivate it).

**Comment by dsyer** [comment] 2020-06-17 16:13
What's your actual use case though? Why do you need the reporoot directory? Maybe you can construct it in a different way?

**Comment by githubyong** [comment] 2020-06-18 05:33
package thin-layout jar in maven online mode, then copy app with reporoot to a maven offline product env , and use "java -jar app.jar --thin.root=reporoot" run it.

**Comment by dsyer** [comment] 2020-06-18 06:10
You can get the same result then, with all snapshots up to date from local cache, if you use `--thin.classpath` to compute the classpath, and then copy those jars to an offline directory and run with `java -cp ...`. That would be my workaround if I needed it - I use that trick much more than `--thin.dryrun` because I like to mess with the classpath, but it works for the default runtime classpath as well.

I'm thinking we might be able to "fix" it by doing something like that in the launcher - changing the implementation of `--thin.dryrun`. But I'm not sure yet if that really works till I try it.

**Comment by githubyong** [comment] 2020-06-18 15:30
It is a high frequently operation in dev life cycle, and then i have to use another stable way to package thin jar : use maven-dependency-plugin to copy dependencies and add class-path to MANIFEST.MF

**Comment by githubyong** [comment] 2020-06-18 15:35
Thanks for your response ~

**Comment by dsyer** [comment] 2020-06-19 15:03
I think I managed to fix it. It works with your sample now anyway for me. Can you test the snapshots?

**Comment by githubyong** [comment] 2020-06-21 16:41
Congratulations!!
I have tested in many scence , it can always follow the maven dependency rule ，and build faster than before.

**Comment by dsyer** [comment] 2020-06-21 17:08
OK, good to know. There are some corner cases I need to try and cover. Then I’ll do a release.

**Comment by dsyer** [comment] 2020-06-23 10:24
I had to change the implementation (1525fb81c). It will be slower again, but more reliable, and you will be able to launch the result offline (which was broken before).

**Comment by dsyer** [comment] 2020-06-23 10:25
I had to change the implementation (1525fb81c). It will be slower again, but more reliable, and you will be able to launch the result offline (which was broken before).

**Comment by githubyong** [comment] 2020-06-23 14:20
Good. It works well.
There is a little problem that if local latest cache is not contentEquals the one in nexus repo, it will copy both to thin root repo.
reproduce steps:
```
1.on pc1, cd thin-lib , run mvn clean install
2.on pc2, cd thin-lib , run mvn clean deploy
3.on pc1, cd thin-app , run mvn clean install -U
$ ll ../reporoot/repository/thin/demo/thin-lib/1.0-SNAPSHOT/
total 26
-rw-r--r-- 1 yong 197121  764  6月 23 22:05 maven-metadata-snapshots.xml
-rw-r--r-- 1 yong 197121   40  6月 23 22:05 maven-metadata-snapshots.xml.sha1
-rw-r--r-- 1 yong 197121  383  6月 23 22:05 resolver-status.properties
-rw-r--r-- 1 yong 197121 4316  6月 23 22:05 thin-lib-1.0-20200623.140438-20.jar
-rw-r--r-- 1 yong 197121   40  6月 23 22:05 thin-lib-1.0-20200623.140438-20.jar.sha1
-rw-r--r-- 1 yong 197121  513  6月 23 22:05 thin-lib-1.0-20200623.140438-20.pom
-rw-r--r-- 1 yong 197121   40  6月 23 22:05 thin-lib-1.0-20200623.140438-20.pom.sha1
-rw-r--r-- 1 yong 197121 4316  6月 23 22:05 thin-lib-1.0-SNAPSHOT.jar
```
the result is right, but thin root repo is not pure.

**Comment by dsyer** [comment] 2020-06-23 15:44
Funny, that's not what I see:

```
$ ls reporoot/repository/thin/demo/thin-lib/1.0-SNAPSHOT/
thin-lib-1.0-SNAPSHOT.jar  thin-lib-1.0-SNAPSHOT.pom
```

I guess when you do `(cd thin-app; mvn clean)` you don't delete the `reporoot` from the parent directory?

**Comment by githubyong** [comment] 2020-06-24 11:18
The maven-clean-plugin would delete reporoot. Step 2 means there is another new snapshot in nexus repo, so local installed cache in not the latest version.
It behaves the same as i delete the reporoot manually before mvn clean install .

**Comment by dsyer** [comment] 2020-06-24 11:36
I see (I think). So the files are identical, and there is no "clean out". I think that's probably the right place to leave it. The duplicate jars is just the way Maven works, and we probably don't want to mess with that.

**Comment by gsapozhn** [comment] 2020-11-18 20:12
Hello,

We use thin-layout and spring-boot-thin-launcher and I think we are running into this issue:

INFO: Extracting dependencies from: URL [jar:file:<...>], with profiles []
Nov 18, 2020 7:00:32 PM org.springframework.boot.loader.thin.MavenSettingsReader loadSettings
INFO: No settings found at: /home/candid/.m2/settings.xml
Nov 18, 2020 7:00:32 PM org.springframework.boot.loader.thin.DependencyResolver dependencies
INFO: Computing dependencies from pom and properties
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:140)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:107)
Caused by: java.lang.RuntimeException: Could not transfer artifact io.grpc:grpc-core:jar:1.16.1 from/to spring-snapshots (https://repo.spring.io/libs-snapshot): Unauthorized (401)

Above, during dependency resolution, a transitive dependency on grpc-core is encountered from repo.spring.io/libs-snapshot, which is now (a recent change as of 11/11/20) password-protected. We do have that JAR locally, but it is ignored.

It appears from the above comments that we would need the fix made in 1525fb8 - however, it's not in any release yet. The last release I see is 1.0.25 from last year and 1525fb8 was committed this summer.

Would it be possible to create a new release?

Thank you,
Gleb Sapozhnikov

**Comment by dsyer** [comment] 2020-11-19 10:22
Wow. It looks like I was in the middle of doing a release on Jun 26 and I somehow forgot to finish. Thanks for the reminder, 1.0.26 should be in Maven Central soon.

**Comment by dsyer** [comment] 2020-11-19 10:26
Can we mark this as closed in 1.0.26?

**Comment by gsapozhn** [comment] 2020-11-19 18:01
Thank you Dave! Will try 1.0.26 as soon as its out and update.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dsyer** [comment] 2020-11-24 13:52
Works for me, so I assume this is fixed.

**Closed by dsyer** 2020-11-24 13:52 UTC

**Comment by gsapozhn** [comment] 2020-11-25 18:06
Just tested it in our environment. It works.

Thank you for making this release!
