### ISSUE TITLE
How can I load the jar package inside the thin jar

### ISSUE THREAD

**Issue by xtaetg** [spring-projects-experimental/spring-boot-thin-launcher#127] opened 2020-01-16 07:33 UTC
If I put the jars generated by the submodules into a thin jar (third-party jars are still placed outside), how can I load the jars generated by these submodules when starting the thin jar

**Comment by dsyer** [comment] 2020-02-14 08:48
You just need them to be in a maven repository. Can be the local cache. What did you try that didn't work? There's a sample in this project that works for instance.

**Comment by dsyer** [comment] 2020-04-08 16:24
Possible duplicate of #15?

**Closed by dsyer** 2020-04-08 16:24 UTC

**Comment by xtaetg** [comment] 2020-05-15 03:04
I dont't want to put them in my maven repository. When I upgrade my programe,I just need to provide only one jar to my customer, otherwise I need to provider more jars and a script to put them into the maven local cache. thanks.

**Comment by dsyer** [comment] 2020-05-15 14:33
Definitely a duplicate then, but the context is useful, thanks.
