### ISSUE TITLE
I want to use local jar replace download dependents

### ISSUE THREAD

**Issue by ifu25** [spring-projects-experimental/spring-boot-thin-launcher#109] opened 2019-04-27 04:59 UTC
when i didn't use thin-launcher, in fat jar i can unzip all dependents jar in `BOOT-INF\lib\`.

![20190427125246383](https://user-images.githubusercontent.com/5575008/56844974-2bec7c80-68ec-11e9-8508-780a6d48b8ff.png)

Now I'm using thin-launcher to build thinJar.
I wang to use local jar from fatJar's `BOOT-INF\lib\`.

like this:
![20190427125734639](https://user-images.githubusercontent.com/5575008/56844976-34dd4e00-68ec-11e9-8cb0-73d1823de8a0.png)

Is there any way to do this?

thank you.

**Comment by dsyer** [comment] 2019-06-12 07:53
Not sure I understand the question. You have all the jars locally, so there's no need for further computation or downloads. Can you not just run `java -cp ...`?

**Comment by dsyer** [comment] 2019-11-06 12:45
Seems like either a non-issue or maybe a duplicate of #78

**Closed by dsyer** 2019-11-06 12:45 UTC
